spring:
  datasource:
    url: jdbc:mysql://database-1.c5o8ia64mo7n.us-east-1.rds.amazonaws.com:3306/hard_drive_heath_predict
    username: root
    password: Thinh2002
    driver-class-name: com.mysql.cj.jdbc.Driver

