spring:
  profiles:
    active: prod
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 51840000000
      refresh-token:
        expiration: 362880000000